### ISSUE TITLE
Use RAII for `SdlStreamEvent`

### ISSUE THREAD

**Issue by PirminTapken** [PirminTapken/go-pong#3]
Use [RAII](http://en.wikipedia.org/wiki/Resource_Acquisition_Is_Initialization) pattern as suggested by @nightlyone in https://github.com/PirminTapken/go-pong/pull/1#discussion_r23603343 for `SdlStreamEvent`

**Comment by nightlyone** [comment]
lets close this :-)

**Comment by PirminTapken** [comment]
Yes, and probably remove the repo at some point. It's probably worth starting anew when I get interested in that again.
